### ISSUE TITLE
Daily image doesn't show

### ISSUE THREAD

**Issue by Pakjesboot12** [Josee9988/Daily-image-discord-bot#14]
Hello there, the bot works fine regarding commands and also posts a picture when the !dimg now is used, but it doesn't post the daily picture every 12 hours :(

**Comment by Josee9988** [comment]
May you give me your server id? You can send me an email privately if you don't want others to see it.
jgracia9988@gmail.com

Thanks and sorry for the issue!

**Comment by Pakjesboot12** [comment]
Sent you an email :)

**Comment by Josee9988** [comment]
It is very weird that it works with the command but not with the scheduler as it uses the same function...
I'll take a deeper look when I buy some time

**Comment by Josee9988** [comment]
Do you get any messages after 12h like your photo was taken on the day ... or something?

**Comment by Josee9988** [comment]
I added a log where the error possibly occurs. I'll be checking 👀

**Comment by Pakjesboot12** [comment]
> 
> 
> Do you get any messages after 12h like your photo was taken on the day ... or something?

No I did not, no messages other when summoned with !dimg now

**Comment by Pakjesboot12** [comment]
> 
> 
> I added a log where the error possibly occurs. I'll be checking 👀

Thanks :D

**Comment by Josee9988** [comment]
I still have this in mind but I'm a bit busy with exams and other things. Sorry for the delay, but I'll do it as soon as I can

**Comment by Pakjesboot12** [comment]
Don't worry, good luck with your exams! (:

**Comment by jhutc82** [comment]
Hello, just wanted to chime in that I also have this issue. I can do "!dimg now" and it posts an image from my google photos, but I don't get automated images. Thanks for your work on this :)

**Comment by Josee9988** [comment]
@jhutc82 I've tested a bit and I know this issue is affecting some of you, I really want to fix this issue but as I said in the issue my time is extremely limited until I finish my course in mid-June/July.
I'll try to buy some time and see if the issue 'shows up' and could be easily fixed and if not I really have to postpone it for at least a month.
I'm sorry about that, but I am the only maintainer of multiple open-source projects and sometimes I just can't fix all the things I want that quick.

Sorry for the delay

**Comment by Pakjesboot12** [comment]
No worries about the delay, good luck with your course :D

**Comment by Josee9988** [comment]
And it is so weird because it works for some of my albums and other like yours do not :/

**Comment by Pakjesboot12** [comment]
I suddenly got like 9 posts in a few minutes without the !dimg now trigger

**Comment by Josee9988** [comment]
I'm debugging the bot and maintaining your server id in a whitelist so yeah, I'm kind of fixing some of the problems 😆

**Comment by Josee9988** [comment]
Sorry for the sudden spam @Pakjesboot12 btw

**Comment by Josee9988** [comment]
@Pakjesboot12 @jhutc82 The bug might be solved. Please tell me if you have new photos every 12hours. You can verify it tomorrow because the next cron job will act in a couple of hours.

**Comment by Pakjesboot12** [comment]
No problem, I'm happy to see progress (:

**Comment by Josee9988** [comment]
@jhutc82 @Pakjesboot12 did the image showed up?

**Comment by Josee9988** [comment]
I've checked the logs and seems like your servers should have received their respective images. So if you guys can confirm it I will gently close this issue 😃

**Comment by Pakjesboot12** [comment]
Yeah I got one at 2:30 am! Good job, it seems to work!

**Comment by jhutc82** [comment]
Yes, I received one automatically yesterday and another just now. Thank you for fixing it! You are awesome!

**Comment by Josee9988** [comment]
@jhutc82 Thanks for the support! Make sure to start the project if you enjoy it ❤️ :D
If anything else happens feel free to post another issue!
