### ISSUE TITLE
Custom text

### ISSUE THREAD

**Issue by AlanPamal** [Josee9988/Daily-image-discord-bot#16]
Hi :D

I wanted to know if u could add the possibility of including a custom text in the daily images, as well as the option of choosing the time and the number of messages that the iamges will be posted.

**By the way, thanks for the bot, it has been very useful.**

**Comment by Josee9988** [comment]
I will add this features as soon as I finish my exams, in 3-4 weeks. But yes, I could do it for sure!!

**Comment by Josee9988** [comment]
Could you create another issue mentioning the number of images per day? So I can easily track the issues (this one for the custom text and the new one for the number of images per day) And you can better see the progress in each one of the tasks.
Many thanks!

**Comment by Josee9988** [comment]
The custom text feature is now added use it like: !dimg sendmsg your new message.

The number of times and hour the images will be sent should be addressed in a new issue.
