### ISSUE TITLE
bot is not verified

### ISSUE THREAD

**Issue by cmod31** [Josee9988/Daily-image-discord-bot#26]
I need a new bot invite link the verification is not there

**Comment by Josee9988** [comment]
Hi, I did the verification process and a discord dev declined it because of "suspicious growth".

So right now there isn't much I can do.

They are ignoring my emails and if they don't accept it no one could invite the bot.

**Comment by cmod31** [comment]
I had this issue before and the developer for it just made a new invite link every time

**Comment by Josee9988** [comment]
I'll check it out, sorry for the inconvenience
