### ISSUE TITLE
[Bug] Validation

### ISSUE THREAD

**Issue by Rinther** [Josee9988/Daily-image-discord-bot#39]
# **🐞 Bug Report**

## **Describe the bug**

* I can't add this to discord due to verification issues on the makers side of things.

---

### **Is this a regression?**

---

### **To Reproduce**

1. Add bot to server
2.
3.
4.

---

### **Expected behaviour**

*

---

### **Media prove**

---

### **Your environment**

* OS: 
* Node version:
* Npm version:
* Browser name and version:

---

### **Additional context**

*

**Comment by Josee9988** [comment]
Please, read the disclaimer found in the readme.

Thanks
